language: python
python:
  - "3.5"
  - "3.6"

install:
  - python setup.py -q install
  - pip install pytest==3.4.1 pylint==1.8.2 pydocstyle==2.1.1 pycodestyle==2.3.1 pytest-cov==2.5.1 coveralls

script:
  - python -m pytest --cov=mumen tests/
  - pydocstyle mumen
  - pydocstyle tests
  - pycodestyle mumen
  - pycodestyle tests
  - pylint --rcfile .pylintrc mumen

after_success:
  - coveralls
